name: CI

on:
  pull_request:
    branches: [ dev, master ]
env:
  node_version: '12.x'
  tf_version: '0.12.26'

jobs:

  env:
    name: Set Env Vars
    runs-on: ubuntu-latest
    steps:

    - name: Setup DEV Environment Variables
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "::set-env name=aws_key::${{ secrets.byu_oit_terraform_dev_key }}"
        echo "::set-env name=aws_secret::${{ secrets.byu_oit_terraform_dev_secret }}"
        echo "::set-env name=tf_working_dir::./terraform-iac/dev/app"

    - name: Setup PRD Environment Variables
      if: github.ref == 'refs/heads/master'
      run: |
        echo "::set-env name=aws_key::${{ secrets.byu_oit_terraform_prd_key }}"
        echo "::set-env name=aws_secret::${{ secrets.byu_oit_terraform_prd_secret }}"
        echo "::set-env name=tf_working_dir::./terraform-iac/prd/app"

    outputs:
      aws_key: ${{ env.aws_key }}
      aws_secret: ${{ env.aws_secret }}
      tf_working_dir: ${{ env.tf_working_dir }} 

  test:
    name: Test 
    runs-on: ubuntu-latest
    steps: 

    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}

    - name: npm install 
      working-directory: src
      run: npm i 

    - name: npm test
      working-directory: src
      run: npm t 

  lint:
    name: Lint 
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}

    - name: npm install 
      working-directory: src
      run: npm i 

    - name: npm lint
      working-directory: src
      run: npm run lint 

  docker:
    name: Docker Build 
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: docker build
      run: |
        docker build src --file src/Dockerfile

  format:
    name: Terraform Format
    runs-on: ubuntu-latest
    needs: env
    steps:

    - uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Terraform Format
      working-directory: ${{ needs.env.outputs.tf_working_dir }}
      run: terraform fmt -check

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: env
    steps:

    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ needs.env.outputs.aws_key }}
        aws-secret-access-key: ${{ needs.env.ouptuts.aws_secret }}
        aws-region: us-west-2

    - name: Build Test Lambda
      working-directory: tst/codedeploy-hooks/after-allow-test-traffic
      run: |
        npm install
        cp -R ../../../.postman .
        zip -r lambda.zip * .postman

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: Terraform Init
      working-directory: ${{ needs.env.outputs.tf_working_dir }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ needs.env.outputs.tf_working_dir }}
      run: terraform plan -var 'image_tag=test' -input=false
